# Generated by Django 5.1.4 on 2026-08-21 07:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.TextField()),
                ('query_type', models.CharField(blank=True, max_length=20)),
                ('retrieved_doc_ids', models.JSONField(default=list)),
                ('num_chunks_retrieved', models.IntegerField(default=0)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('faithfulness', models.FloatField(blank=True, null=True)),
                ('answer_relevancy', models.FloatField(blank=True, null=True)),
                ('context_precision', models.FloatField(blank=True, null=True)),
                ('context_recall', models.FloatField(blank=True, null=True)),
                ('evaluation_error', models.TextField(blank=True)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='query_log', to='chat.message')),
            ],
            options={
                'db_table': 'query_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
