# Generated by Django 5.1.4 on 2026-08-21 04:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other / Prefer not to say')], max_length=10)),
                ('state', models.CharField(blank=True, choices=[('AN', 'Andaman and Nicobar Islands'), ('AP', 'Andhra Pradesh'), ('AR', 'Arunachal Pradesh'), ('AS', 'Assam'), ('BR', 'Bihar'), ('CH', 'Chandigarh'), ('CT', 'Chhattisgarh'), ('DN', 'Dadra and Nagar Haveli and Daman and Diu'), ('DL', 'Delhi'), ('GA', 'Goa'), ('GJ', 'Gujarat'), ('HR', 'Haryana'), ('HP', 'Himachal Pradesh'), ('JK', 'Jammu and Kashmir'), ('JH', 'Jharkhand'), ('KA', 'Karnataka'), ('KL', 'Kerala'), ('LA', 'Ladakh'), ('LD', 'Lakshadweep'), ('MP', 'Madhya Pradesh'), ('MH', 'Maharashtra'), ('MN', 'Manipur'), ('ML', 'Meghalaya'), ('MZ', 'Mizoram'), ('NL', 'Nagaland'), ('OD', 'Odisha'), ('PY', 'Puducherry'), ('PB', 'Punjab'), ('RJ', 'Rajasthan'), ('SK', 'Sikkim'), ('TN', 'Tamil Nadu'), ('TG', 'Telangana'), ('TR', 'Tripura'), ('UP', 'Uttar Pradesh'), ('UK', 'Uttarakhand'), ('WB', 'West Bengal')], db_index=True, max_length=3)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=6)),
                ('is_urban', models.BooleanField(blank=True, help_text='True = Urban, False = Rural', null=True)),
                ('social_category', models.CharField(blank=True, choices=[('GENERAL', 'General'), ('OBC', 'Other Backward Class (OBC)'), ('SC', 'Scheduled Caste (SC)'), ('ST', 'Scheduled Tribe (ST)'), ('EWS', 'Economically Weaker Section (EWS)')], db_index=True, max_length=10)),
                ('annual_income', models.DecimalField(blank=True, decimal_places=2, help_text='Annual household income in INR', max_digits=12, null=True)),
                ('is_bpl', models.BooleanField(default=False, help_text='Is the user a BPL cardholder?', verbose_name='Below Poverty Line')),
                ('has_ration_card', models.BooleanField(default=False)),
                ('ration_card_type', models.CharField(blank=True, choices=[('APL', 'APL'), ('BPL', 'BPL'), ('AAY', 'AAY (Antyodaya)')], max_length=10)),
                ('occupation', models.CharField(blank=True, choices=[('FARMER', 'Farmer / Agricultural Worker'), ('AGRICULTURAL_LABORER', 'Agricultural Laborer'), ('SELF_EMPLOYED', 'Self-Employed / Business'), ('PRIVATE_EMPLOYEE', 'Private Sector Employee'), ('GOVERNMENT_EMPLOYEE', 'Government Employee'), ('UNEMPLOYED', 'Unemployed'), ('STUDENT', 'Student'), ('HOMEMAKER', 'Homemaker'), ('DAILY_WAGER', 'Daily Wager'), ('ARTISAN', 'Artisan / Craftsperson'), ('RETIRED', 'Retired'), ('OTHER', 'Other')], db_index=True, max_length=30)),
                ('education_level', models.CharField(blank=True, choices=[('NO_FORMAL', 'No Formal Education'), ('PRIMARY', 'Primary (Class 1-5)'), ('MIDDLE', 'Middle (Class 6-8)'), ('SECONDARY', 'Secondary (Class 9-10)'), ('HIGHER_SECONDARY', 'Higher Secondary (Class 11-12)'), ('DIPLOMA', 'Diploma / ITI'), ('GRADUATE', 'Graduate (UG)'), ('POST_GRADUATE', 'Post Graduate (PG)'), ('DOCTORATE', 'Doctorate / PhD')], max_length=20)),
                ('is_student', models.BooleanField(default=False)),
                ('institution_name', models.CharField(blank=True, max_length=255)),
                ('has_disability', models.BooleanField(default=False)),
                ('disability_percentage', models.IntegerField(blank=True, help_text='Disability percentage (0-100)', null=True)),
                ('is_ex_serviceman', models.BooleanField(default=False)),
                ('is_minority', models.BooleanField(default=False)),
                ('is_widow', models.BooleanField(default=False)),
                ('is_single_girl_child', models.BooleanField(default=False)),
                ('land_holding_acres', models.DecimalField(blank=True, decimal_places=2, help_text='Agricultural land holding in acres', max_digits=8, null=True)),
                ('is_marginal_farmer', models.BooleanField(default=False, help_text='< 1 hectare')),
                ('is_small_farmer', models.BooleanField(default=False, help_text='1–2 hectares')),
                ('family_size', models.IntegerField(blank=True, null=True)),
                ('number_of_children', models.IntegerField(blank=True, null=True)),
                ('is_female_headed_household', models.BooleanField(default=False)),
                ('additional_attributes', models.JSONField(blank=True, default=dict, help_text='Flexible JSON for any scheme-specific attributes')),
                ('profile_completion_score', models.IntegerField(default=0, help_text='0–100 completion score')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'user_profiles',
            },
        ),
    ]
