# Generated by Django 5.1.4 on 2026-08-21 04:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, help_text='e.g. Department of Agricultural Research and Education', max_length=300)),
                ('short_code', models.CharField(blank=True, max_length=50)),
                ('website_url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'scheme_departments',
                'ordering': ['ministry', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, help_text='e.g. Ministry of Agriculture and Farmers Welfare', max_length=300, unique=True)),
                ('short_code', models.CharField(blank=True, help_text='e.g. MoA&FW, MoHFW, MoE', max_length=50)),
                ('website_url', models.URLField(blank=True, max_length=500)),
                ('is_central', models.BooleanField(default=True, help_text='True for Central Ministries, False for State Ministries')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ministry',
                'verbose_name_plural': 'Ministries',
                'db_table': 'scheme_ministries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SchemeCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('icon', models.CharField(blank=True, help_text='e.g. 🌾, 🎓, 🏥, or icon class name', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scheme Category',
                'verbose_name_plural': 'Scheme Categories',
                'db_table': 'scheme_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text='e.g. UP, MH, DL, KA', max_length=10, unique=True)),
                ('name', models.CharField(db_index=True, help_text='e.g. Uttar Pradesh, Delhi', max_length=100, unique=True)),
                ('is_union_territory', models.BooleanField(default=False)),
                ('official_portal_url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'State / UT',
                'verbose_name_plural': 'States & UTs',
                'db_table': 'scheme_states',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GovernmentScheme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, help_text='Official name of scheme', max_length=500)),
                ('slug', models.SlugField(max_length=500, unique=True)),
                ('short_title', models.CharField(blank=True, db_index=True, help_text='e.g. PM-KISAN, PMAY-G', max_length=100)),
                ('description', models.TextField(help_text='Detailed overview and objectives of the scheme')),
                ('scheme_type', models.CharField(choices=[('CENTRAL_SECTOR', 'Central Sector Scheme (100% Central)'), ('CENTRALLY_SPONSORED', 'Centrally Sponsored Scheme (Cost Shared)'), ('STATE_GOVERNMENT', 'State Government Scheme'), ('UT_ADMINISTRATION', 'Union Territory Scheme'), ('PUBLIC_PRIVATE', 'Public-Private Partnership')], db_index=True, default='CENTRAL_SECTOR', max_length=30)),
                ('target_beneficiaries', models.TextField(blank=True, help_text='Target group summary (e.g. Small & Marginal farmers, SC/ST students)')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active / Accepting Applications'), ('INACTIVE', 'Temporarily Inactive'), ('UPCOMING', 'Announced / Upcoming'), ('DISCONTINUED', 'Discontinued'), ('MERGED', 'Merged into Another Scheme')], db_index=True, default='ACTIVE', max_length=20)),
                ('version', models.CharField(default='1.0', help_text='Current scheme version', max_length=20)),
                ('launch_date', models.DateField(blank=True, null=True)),
                ('valid_upto', models.DateField(blank=True, help_text='Scheme sunset date or fiscal end date', null=True)),
                ('important_dates', models.JSONField(blank=True, default=dict, help_text='Dictionary of milestones, deadlines, and cycles')),
                ('official_application_url', models.URLField(blank=True, max_length=1000)),
                ('official_source_url', models.URLField(blank=True, max_length=1000)),
                ('funding_pattern', models.CharField(blank=True, help_text='e.g. 100% Central, 60:40 Centre:State', max_length=200)),
                ('helpline_number', models.CharField(blank=True, max_length=100)),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of keywords for semantic and sparse discovery')),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schemes', to='schemes.department')),
                ('ministry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schemes', to='schemes.ministry')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schemes', to='schemes.schemecategory')),
                ('state', models.ForeignKey(blank=True, help_text='Specified for state-specific schemes, Null for Pan-India schemes', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schemes', to='schemes.state')),
            ],
            options={
                'verbose_name': 'Government Scheme',
                'verbose_name_plural': 'Government Schemes',
                'db_table': 'government_schemes',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='ministry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='schemes.ministry'),
        ),
        migrations.CreateModel(
            name='RequiredDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_name', models.CharField(help_text='e.g. Aadhaar Card (Mobile Linked)', max_length=300)),
                ('document_type', models.CharField(choices=[('IDENTITY_PROOF', 'Identity Proof (Aadhaar, Voter ID, Passport)'), ('ADDRESS_PROOF', 'Proof of Address (Electricity Bill, Ration Card)'), ('INCOME_PROOF', 'Income Certificate / Salary Slip'), ('CASTE_PROOF', 'Caste / Category Certificate (SC/ST/OBC/EWS)'), ('LAND_RECORD', 'Land Ownership Record / Khasra-Khatauni'), ('BANK_DETAILS', 'Bank Account Passbook / Cancelled Cheque (Aadhaar Seeded)'), ('EDUCATIONAL_CERTIFICATE', 'Marksheet / Degree / Enrollment Proof'), ('DISABILITY_CERTIFICATE', 'UDID / Disability Medical Certificate'), ('AGE_PROOF', 'Birth Certificate / 10th Certificate'), ('PASSPORT_PHOTO', 'Passport Size Photographs'), ('OTHER', 'Other Scheme Specific Affidavit / Undertaking')], default='IDENTITY_PROOF', max_length=30)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, help_text='Details such as self-attestation, validity period, or issuing department')),
                ('issuing_authority', models.CharField(blank=True, help_text='e.g. UIDAI, Revenue Department / Tehsildar, Commercial Bank', max_length=200)),
                ('accepted_formats', models.CharField(blank=True, default='PDF, JPG, PNG', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_documents', to='schemes.governmentscheme')),
            ],
            options={
                'verbose_name': 'Required Document',
                'verbose_name_plural': 'Required Documents',
                'db_table': 'scheme_required_documents',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SchemeBenefit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('benefit_type', models.CharField(choices=[('DIRECT_BENEFIT_TRANSFER', 'Direct Benefit Transfer (DBT Cash)'), ('SUBSIDY', 'Financial Subsidy / Grant'), ('LOAN_CREDIT', 'Concessional Loan / Credit Support'), ('INSURANCE_COVER', 'Health / Life / Crop Insurance'), ('SCHOLARSHIP', 'Educational Scholarship / Stipend'), ('IN_KIND_GOODS', 'In-Kind Goods / Equipment / Ration'), ('PENSION', 'Monthly Social Security Pension'), ('TRAINING_SKILL', 'Skill Training & Certification'), ('TAX_EXEMPTION', 'Tax Exemption / Rebate'), ('HOUSING_UNIT', 'Pucca House / Shelter Construction'), ('OTHER', 'Other Non-Financial / Advisory Benefit')], default='DIRECT_BENEFIT_TRANSFER', max_length=30)),
                ('title', models.CharField(help_text='e.g. ₹6,000 per year in 3 equal installments of ₹2,000', max_length=300)),
                ('description', models.TextField(blank=True, help_text='Detailed coverage, terms, and caps')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Direct monetary amount in INR (if applicable)', max_digits=12, null=True)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('disbursement_frequency', models.CharField(choices=[('ONE_TIME', 'One-Time Grant'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly (4 installments/year)'), ('TRI_ANNUAL', 'Every 4 Months (3 installments/year e.g. PM-Kisan)'), ('ANNUAL', 'Annual'), ('MILESTONE_BASED', 'Linked to Construction / Course Milestones'), ('EVENT_BASED', 'Upon Occurrence of Event (e.g. Hospitalization, Calamity)')], default='ONE_TIME', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='schemes.governmentscheme')),
            ],
            options={
                'verbose_name': 'Scheme Benefit',
                'verbose_name_plural': 'Scheme Benefits',
                'db_table': 'scheme_benefits',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SchemeEligibilityRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_group', models.PositiveIntegerField(default=1, help_text='Rules within the same group are combined with AND. Separate groups are combined with OR.')),
                ('criterion_key', models.CharField(db_index=True, help_text='Maps to UserProfile fields (e.g. age, annual_income, state, social_category, is_bpl, occupation, land_holding_acres, has_disability, gender, education_level, is_student)', max_length=100)),
                ('operator', models.CharField(choices=[('EQUALS', 'Equals (==)'), ('NOT_EQUALS', 'Not Equals (!=)'), ('GREATER_THAN', 'Greater Than (>)'), ('LESS_THAN', 'Less Than (<)'), ('GTE', 'Greater Than or Equal (>=)'), ('LTE', 'Less Than or Equal (<=)'), ('IN_LIST', 'In List (Any of)'), ('NOT_IN_LIST', 'Not In List'), ('CONTAINS', 'Contains Substring'), ('BOOLEAN_TRUE', 'Must Be True'), ('BOOLEAN_FALSE', 'Must Be False'), ('BETWEEN', 'Between Min and Max'), ('EXISTS', 'Field Must Exist / Be Provided')], default='EQUALS', max_length=25)),
                ('value', models.CharField(blank=True, help_text='Target value for single-value comparisons or comma-separated list', max_length=500)),
                ('min_value', models.CharField(blank=True, help_text='Lower bound for BETWEEN operator', max_length=100, null=True)),
                ('max_value', models.CharField(blank=True, help_text='Upper bound for BETWEEN operator', max_length=100, null=True)),
                ('data_type', models.CharField(choices=[('INTEGER', 'Integer Number'), ('DECIMAL', 'Decimal / Currency'), ('STRING', 'Text String / Code'), ('BOOLEAN', 'Boolean (True/False)'), ('DATE', 'Date (YYYY-MM-DD)'), ('LIST', 'List / Array of Values')], default='STRING', max_length=15)),
                ('is_mandatory', models.BooleanField(default=True, help_text='If mandatory, failing this rule disqualifies the applicant')),
                ('disqualification_condition', models.BooleanField(default=False, help_text='If True, matching this condition DISQUALIFIES the applicant (e.g. Income tax payers ineligible)')),
                ('rule_description', models.TextField(help_text='Human-readable explanation of this criteria')),
                ('order', models.PositiveIntegerField(default=0)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_rules', to='schemes.governmentscheme')),
            ],
            options={
                'verbose_name': 'Eligibility Rule',
                'verbose_name_plural': 'Eligibility Rules',
                'db_table': 'scheme_eligibility_rules',
                'ordering': ['rule_group', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SchemeSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('OFFICIAL_GAZETTE', 'Official Gazette Notification'), ('MINISTRY_GUIDELINE', 'Ministry Operational Guidelines'), ('PORTAL_WEBPAGE', 'Official Government Portal Webpage'), ('PRESS_RELEASE', 'PIB / Official Press Release'), ('ACT_ORDINANCE', 'Parliamentary / State Legislative Act'), ('SCHEME_BROCHURE', 'Official Citizen Brochure / FAQ')], default='MINISTRY_GUIDELINE', max_length=30)),
                ('title', models.CharField(help_text='e.g. Operational Guidelines of PM-KISAN Scheme (Revised 2024)', max_length=300)),
                ('url', models.URLField(help_text='Official direct document link or portal URL', max_length=1000)),
                ('document_reference_number', models.CharField(blank=True, help_text='e.g. F.No. 1-1/2020-Credit-II', max_length=200)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=True)),
                ('retrieved_at', models.DateTimeField(auto_now_add=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='schemes.governmentscheme')),
            ],
            options={
                'verbose_name': 'Scheme Source / Citation',
                'verbose_name_plural': 'Scheme Sources / Citations',
                'db_table': 'scheme_sources',
                'ordering': ['-retrieved_at'],
            },
        ),
        migrations.AddField(
            model_name='ministry',
            name='state',
            field=models.ForeignKey(blank=True, help_text='Specified if state-level ministry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ministries', to='schemes.state'),
        ),
        migrations.CreateModel(
            name='ApplicationProcedure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('ONLINE', 'Online Application Portal'), ('OFFLINE', 'Offline Submission at Government Office'), ('HYBRID', 'Online Registration + Physical Document Verification'), ('CSC_PORTAL', 'Common Service Centre (CSC) / Village Level Entrepreneur')], default='ONLINE', max_length=20)),
                ('step_number', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(help_text='e.g. Step 1: Online Farmer Registration', max_length=300)),
                ('description', models.TextField(help_text='Clear action steps to complete this stage')),
                ('portal_url', models.URLField(blank=True, help_text='Direct link for this application stage', max_length=1000)),
                ('office_name', models.CharField(blank=True, help_text='Designated office if offline (e.g. Block Agriculture Office, District Welfare Officer)', max_length=300)),
                ('processing_time_days', models.PositiveIntegerField(blank=True, help_text='Expected processing & approval turnaround in days', null=True)),
                ('fee_inr', models.DecimalField(decimal_places=2, default=0.0, help_text='Application / Processing fee (0 if free)', max_digits=10)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_steps', to='schemes.governmentscheme')),
            ],
            options={
                'verbose_name': 'Application Step',
                'verbose_name_plural': 'Application Steps',
                'db_table': 'scheme_application_steps',
                'ordering': ['step_number'],
                'unique_together': {('scheme', 'step_number')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('ministry', 'name')},
        ),
        migrations.CreateModel(
            name='SchemeVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.CharField(help_text='e.g. 1.0, 2.0, 2024-R1', max_length=50)),
                ('change_summary', models.TextField(help_text='Key changes introduced in this revision')),
                ('effective_from', models.DateField(help_text='Start date of this revision')),
                ('effective_to', models.DateField(blank=True, help_text='End date (null if current active version)', null=True)),
                ('snapshot_data', models.JSONField(default=dict, help_text='Complete structured snapshot (rules, benefits, documents, application steps) at this version')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheme_version_edits', to=settings.AUTH_USER_MODEL)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='schemes.governmentscheme')),
            ],
            options={
                'verbose_name': 'Scheme Version',
                'verbose_name_plural': 'Scheme Versions',
                'db_table': 'scheme_versions',
                'ordering': ['-created_at'],
                'unique_together': {('scheme', 'version_number')},
            },
        ),
        migrations.AddIndex(
            model_name='governmentscheme',
            index=models.Index(fields=['status', 'scheme_type'], name='government__status_ccd176_idx'),
        ),
        migrations.AddIndex(
            model_name='governmentscheme',
            index=models.Index(fields=['category', 'status'], name='government__categor_5649a7_idx'),
        ),
        migrations.AddIndex(
            model_name='governmentscheme',
            index=models.Index(fields=['state', 'status'], name='government__state_i_45e4dd_idx'),
        ),
    ]
