# Generated by Django 5.1.4 on 2026-08-21 05:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schemes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GovDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('ministry', models.CharField(blank=True, db_index=True, max_length=300)),
                ('department', models.CharField(blank=True, max_length=300)),
                ('state', models.CharField(blank=True, help_text='State / UT if state-specific scheme', max_length=100)),
                ('category', models.CharField(choices=[('AGRICULTURE', 'Agriculture'), ('EDUCATION', 'Education'), ('HEALTH', 'Health'), ('HOUSING', 'Housing'), ('SOCIAL_WELFARE', 'Social Welfare'), ('EMPLOYMENT', 'Employment'), ('WOMEN_CHILD', 'Women & Child Development'), ('SKILL_DEVELOPMENT', 'Skill Development'), ('FINANCIAL_INCLUSION', 'Financial Inclusion'), ('ENTREPRENEURSHIP', 'Entrepreneurship'), ('DISABILITY', 'Disability'), ('MINORITY', 'Minority Welfare'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=30)),
                ('document_version', models.CharField(default='1.0', help_text='Version / revision of the document', max_length=50)),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('language', models.CharField(default='en', max_length=10)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('file_path', models.CharField(blank=True, max_length=1000)),
                ('file_name', models.CharField(blank=True, max_length=500)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('file_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Upload'), ('PROCESSING', 'Processing'), ('CHUNKING', 'Chunking'), ('EMBEDDING', 'Embedding'), ('EXTRACTING', 'Extracting Schemes'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('processing_error', models.TextField(blank=True)),
                ('total_chunks', models.IntegerField(default=0)),
                ('total_tokens', models.BigIntegerField(default=0)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('chunking_strategy', models.CharField(default='recursive', max_length=50)),
                ('embedding_model', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='schemes.governmentscheme')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Government Document',
                'verbose_name_plural': 'Government Documents',
                'db_table': 'gov_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_index', models.IntegerField()),
                ('content', models.TextField()),
                ('chunk_type', models.CharField(choices=[('TEXT', 'Text Paragraph'), ('TABLE', 'Table'), ('HEADING', 'Heading'), ('LIST', 'List'), ('ELIGIBILITY', 'Eligibility Section'), ('BENEFITS', 'Benefits Section'), ('PROCEDURE', 'Procedure Section'), ('DOCUMENTS', 'Required Documents')], default='TEXT', max_length=20)),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('section_title', models.CharField(blank=True, max_length=500)),
                ('heading_path', models.CharField(blank=True, max_length=1000)),
                ('token_count', models.IntegerField(default=0)),
                ('char_count', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='ministry, scheme_name, year, language, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.govdocument')),
            ],
            options={
                'verbose_name': 'Document Chunk',
                'verbose_name_plural': 'Document Chunks',
                'db_table': 'document_chunks',
                'ordering': ['document', 'chunk_index'],
            },
        ),
        migrations.AddIndex(
            model_name='govdocument',
            index=models.Index(fields=['status', 'category'], name='gov_documen_status_b98d72_idx'),
        ),
        migrations.AddIndex(
            model_name='govdocument',
            index=models.Index(fields=['ministry'], name='gov_documen_ministr_4be347_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['document', 'chunk_type'], name='document_ch_documen_8a3ad2_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['page_number'], name='document_ch_page_nu_91bcc3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentchunk',
            unique_together={('document', 'chunk_index')},
        ),
    ]
